coverage_service: coveralls
scheme: BluePlaquesLondon
source_directory: BluePlaquesLondon
workspace: BluePlaquesLondon.xcworkspace
ignore:
  - BluePlaquesLondonTests/*
  - BluePlaquesLondon/Dependencies/*
