coverage_service: coveralls
xcodeproj: BluePlaquesLondon.xcodeproj
scheme: BluePlaquesLondon
source_directory: BluePlaquesLondon
ignore:
  - BluePlaquesLondonTests/*
  - BluePlaquesLondon/Dependencies/*
