language: objective-c
before_install:
  - chmod a+x travis/before_script.sh
  - git submodule sync
  - git submodule update --init --recursive
install: bundle install --without=documentation --path ../travis_bundle_dir
before_script: travis/before_script.sh
script: bundle exec fastlane test
after_success: bundle exec slather
