language: objective-c
before_install:
  - git submodule sync
  - git submodule update --init --recursive
  - brew update
  - gem install cocoapods
install:
  - pod install
  - bundle install --without=documentation --path ../travis_bundle_dir
script: xcodebuild -workspace BluePlaquesLondon.xcworkspace -scheme BluePlaquesLondon -sdk iphonesimulator test
after_success: bundle exec slather
