require 'dotenv'
Dotenv.load('../.env')

default_platform(:ios)

lane :test do
  scan(
    scheme: "BluePlaquesLondon",
    device: "iPhone 16 Pro",
    deployment_target_version: "18.0"
  )
end

lane :build do
  gym(
    scheme: "BluePlaquesLondon",
    export_method: "development",
    xcargs: "-allowProvisioningUpdates"
  )
end

lane :beta do
  gym(
    scheme: "BluePlaquesLondon",
    export_method: "app-store",
    xcargs: "-allowProvisioningUpdates"
  )
  upload_to_testflight(
    skip_waiting_for_build_processing: true
  )
end

lane :release do
  build
  upload_to_app_store
end
