default_platform(:ios)

lane :test do
  scan(
    scheme: "BluePlaquesLondon",
    device: "iPhone 16 Pro",
    deployment_target_version: "18.0",
    code_coverage: true
  )
end

lane :screenshots do
  snapshot
end

lane :setup do
  # Generate GoogleService-Info.plist from template
  sh "sed 's/FIREBASE_API_KEY_PLACEHOLDER/#{ENV['FIREBASE_API_KEY']}/g' ../BluePlaquesLondon/Resources/GoogleService-Info-template.plist > ../BluePlaquesLondon/Resources/GoogleService-Info.plist"
  # Generate APIKeys.plist from template  
  sh "sed 's/GOOGLE_MAPS_API_KEY_PLACEHOLDER/#{ENV['GOOGLE_MAPS_API_KEY']}/g' ../BluePlaquesLondon/Resources/APIKeys.plist > ../BluePlaquesLondon/Resources/APIKeys-temp.plist && mv ../BluePlaquesLondon/Resources/APIKeys-temp.plist ../BluePlaquesLondon/Resources/APIKeys.plist"
end

lane :build do
  gym(
    scheme: "BluePlaquesLondon",
    export_method: "development",
    xcargs: "-allowProvisioningUpdates"
  )
end

lane :beta do
  setup
  increment_build_number(xcodeproj: "BluePlaquesLondon.xcodeproj")
  gym(
    scheme: "BluePlaquesLondon",
    export_method: "app-store",
    xcargs: "-allowProvisioningUpdates"
  )
  upload_to_testflight(
    api_key: app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: "fastlane/api_keys/AuthKey_#{ENV['APP_STORE_CONNECT_API_KEY_KEY_ID']}.p8"
    ),
    changelog: "Bug fixes and improvements",
    skip_waiting_for_build_processing: true
  )
end

lane :release do
  setup
  increment_version_number(bump_type: "patch")
  increment_build_number(xcodeproj: "BluePlaquesLondon.xcodeproj")
  gym(
    scheme: "BluePlaquesLondon",
    export_method: "app-store",
    xcargs: "-allowProvisioningUpdates"
  )
  upload_to_app_store(
    api_key: app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: "fastlane/api_keys/AuthKey_#{ENV['APP_STORE_CONNECT_API_KEY_KEY_ID']}.p8"
    ),
    force: true,
    submit_for_review: false
  )
end
