name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.7
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        bundle install
        pod install
    
    - name: Deploy to TestFlight
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      run: bundle exec fastlane beta